version: '3.8'

x-common-environment: &common-environment
  NODE_ENV: production
  RPC_URLS: ${RPC_URLS}
  BSC_MAINNET_RPC_URLS: ${BSC_MAINNET_RPC_URLS}
  BSC_MAINNET_FORK_RPC_URLS: ${BSC_MAINNET_FORK_RPC_URLS}
  REDIS_HOST: redis-server
  REDIS_PASSWORD: ${REDIS_PASSWORD}

services:
  redis-server:
    image: redis:latest
    mem_limit: 350m
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

  collector:
    build:
      context: .
      dockerfile: packages/collector/Dockerfile
    environment:
      <<: *common-environment
      FORK_RPC_URL: ${FORK_RPC_URL}
      NODE_OPTIONS: --max_old_space_size=6144
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 7168M

  liquidation-checker-cs2-skins:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: CS2 Skins
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-spotify-the-weeknd:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Spotify The Weeknd
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-strategic-reserve-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Strategic Reserve Index
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-bnb-usd:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: BNB/USD
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-binance-alpha-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Binance Alpha Index
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-ai-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: AI Index
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-usa-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: USA Index
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-btc-dominance:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: BTC Dominance
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-btc-usd:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: BTC/USD
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-eth-usd:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: ETH/USD
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-sol-usd:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: SOL/USD
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-aster-myx:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Aster/MYX
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  executor-1:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    environment:
      <<: *common-environment
      PRIVATE_KEYS: ${PRIVATE_KEYS_1}
      NODE_OPTIONS: --max_old_space_size=204
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  executor-2:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    environment:
      <<: *common-environment
      PRIVATE_KEYS: ${PRIVATE_KEYS_2}
      NODE_OPTIONS: --max_old_space_size=204
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  monitor:
    build:
      context: .
      dockerfile: packages/monitor/Dockerfile
    environment:
      <<: *common-environment
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  health-checker:
    build:
      context: .
      dockerfile: packages/health-checker/Dockerfile
    restart: unless-stopped
    environment:
      <<: *common-environment
    ports:
      - '2025:2025'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    
  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
