version: '3.8'

x-common-environment: &common-environment
  NODE_ENV: production
  RPC_URLS: ${RPC_URLS}
  REDIS_HOST: redis-server
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  MULTICALL_BATCH_SIZE: ${MULTICALL_BATCH_SIZE}
  RPC_FIRST_PROBABILITY: ${RPC_FIRST_PROBABILITY}
  WORKERS_AMOUNT: ${WORKERS_AMOUNT}

services:
  redis-server:
    image: redis:latest
    mem_limit: 350m
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}

  collector:
    build:
      context: .
      dockerfile: packages/collector/Dockerfile
    environment:
      <<: *common-environment
      FORK_RPC_URL: ${FORK_RPC_URL}
    depends_on:
      - redis-server

  liquidation-checker-eth-dominance:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: ETH Dominance
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_ETH_DOMINANCE}
    depends_on:
      - redis-server

  liquidation-checker-btc-dominance:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: BTC Dominance
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_BTC_DOMINANCE}
    depends_on:
      - redis-server

  liquidation-checker-quantum-cats:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Quantum Cats
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_QUANTUM_CATS}
    depends_on:
      - redis-server

  liquidation-checker-cs2-skins:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: CS2 Skins
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_CS2_SKINS}
    depends_on:
      - redis-server

  liquidation-checker-bitcoin-frogs:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Bitcoin Frogs
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_BITCOIN_FROGS}
    depends_on:
      - redis-server

  liquidation-checker-ink:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Ink
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_INK}
    depends_on:
      - redis-server

  liquidation-checker-nodemonkes:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: NodeMonkes
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_NODEMONKES}
    depends_on:
      - redis-server

  executor-1:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    environment:
      <<: *common-environment
      PRIVATE_KEYS: ${PRIVATE_KEYS_1}
    depends_on:
      - redis-server

  executor-2:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    environment:
      <<: *common-environment
      PRIVATE_KEYS: ${PRIVATE_KEYS_2}
    depends_on:
      - redis-server
    
