version: '3.8'

x-common-environment: &common-environment
  NODE_ENV: production
  RPC_URLS: ${RPC_URLS}
  REDIS_HOST: redis-server
  REDIS_PASSWORD: ${REDIS_PASSWORD}

services:
  redis-server:
    image: redis:latest
    mem_limit: 350m
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

  collector:
    build:
      context: .
      dockerfile: packages/collector/Dockerfile
    environment:
      <<: *common-environment
      FORK_RPC_URL: ${FORK_RPC_URL}
      NODE_OPTIONS: --max_old_space_size=3072
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 4096M

  liquidation-checker-eth-dominance:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: ETH Dominance
      NODE_OPTIONS: --max_old_space_size=819
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M

  liquidation-checker-btc-dominance:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: BTC Dominance
      NODE_OPTIONS: --max_old_space_size=819
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M

  liquidation-checker-quantum-cats:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Quantum Cats
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-cs2-skins:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: CS2 Skins
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-checker-bitcoin-frogs:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Bitcoin Frogs
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-ink:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Ink
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-nodemonkes:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: NodeMonkes
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-evindex:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: EvIndex
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-aiindex:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: AiIndex
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-ethsol:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: EthSol
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  executor-1:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    environment:
      <<: *common-environment
      PRIVATE_KEYS: ${PRIVATE_KEYS_1}
      NODE_OPTIONS: --max_old_space_size=204
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  executor-2:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    environment:
      <<: *common-environment
      PRIVATE_KEYS: ${PRIVATE_KEYS_2}
      NODE_OPTIONS: --max_old_space_size=204
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  monitor:
    build:
      context: .
      dockerfile: packages/monitor/Dockerfile
    environment:
      <<: *common-environment
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    
  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
