version: '3.8'
services:
  redis-server:
    image: redis:latest
    mem_limit: 350m
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}

  collector:
    build:
      context: .
      dockerfile: packages/collector/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      RPC_URLS: ${RPC_URLS}
      REDIS_HOST: redis-server
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis-server

  liquidation-checker:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production

  executor:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
