version: '3.8'

x-common-environment: &common-environment
  NODE_ENV: production
  RPC_URLS: ${RPC_URLS}
  BSC_TESTNET_RPC_URLS: ${BSC_TESTNET_RPC_URLS}
  BSC_TESTNET_FORK_RPC_URLS: ${BSC_TESTNET_FORK_RPC_URLS}
  REDIS_HOST: redis-server
  REDIS_PASSWORD: ${REDIS_PASSWORD}

services:
  redis-server:
    image: redis:latest
    mem_limit: 350m
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

  collector:
    build:
      context: .
      dockerfile: packages/collector/Dockerfile
    environment:
      <<: *common-environment
      FORK_RPC_URL: ${FORK_RPC_URL}
      NODE_OPTIONS: --max_old_space_size=6144
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 7168M

  liquidation-checker-eth-dominance:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: ETH Dominance
      NODE_OPTIONS: --max_old_space_size=819
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M

  liquidation-checker-btc-dominance:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: BTC Dominance
      NODE_OPTIONS: --max_old_space_size=819
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M

  liquidation-checker-quantum-cats:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Quantum Cats
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-cs2-skins:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: CS2 Skins
      NODE_OPTIONS: --max_old_space_size=614
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-checker-bitcoin-frogs:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Bitcoin Frogs
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-ink:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Ink
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-nodemonkes:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: NodeMonkes
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-evindex:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: EvIndex
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-aiindex:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: AiIndex
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-ethsol:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: EthSol
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-cs-rifles:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: CS Rifles
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-cs-knives:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: CS Knives
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-cs-knives-rifles:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: CS Knives Rifles
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-cats-dogs-2:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Cats Dogs 2
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-cats-frogs:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Cats Frogs
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-frogs-dogs:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Frogs Dogs
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-real-estate:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Real Estate
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-super-eth:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Super Eth
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-carlsen:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Carlsen
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-hikaru:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Hikaru
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-spotify-lana-del-rey:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Spotify Lana Del Rey
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-bera-nfts:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Bera NFTs Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-ai-agents:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: AI Agents Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-defi-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Defi Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-layer1-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Layer 1 Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-layer2-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Layer 2 Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-layer1-vs-layer2:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Layer1 Vs Layer2 Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-honeycomb-jars:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: HoneyComb and Jars NFT Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-ibgt-bera:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: iBGT BERA
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-bullas:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Bullas
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-amouranth-peachjars:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Amouranth vs peachJars
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-jessicanigri-monalita:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Jessicanigri vs Monalita
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-monalita-elvasnaps:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Monalita vs Elvasnaps
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-binance-alpha-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Binance Alpha Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-bnb-usd:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: BNB / USD
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-made-in-usa-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Made In USA Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-sol-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: SOL Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-sol-usd:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: SOL/USD
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-memes-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Memes Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-spotify-the-weeknd-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Spotify The Weeknd Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-spotify-billie-eilish-index:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Spotify Billie Eilish Index
      NODE_OPTIONS: --max_old_space_size=409
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  executor-1:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    environment:
      <<: *common-environment
      PRIVATE_KEYS: ${PRIVATE_KEYS_1}
      NODE_OPTIONS: --max_old_space_size=204
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  executor-2:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    environment:
      <<: *common-environment
      PRIVATE_KEYS: ${PRIVATE_KEYS_2}
      NODE_OPTIONS: --max_old_space_size=204
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  monitor:
    build:
      context: .
      dockerfile: packages/monitor/Dockerfile
    environment:
      <<: *common-environment
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  health-checker:
    build:
      context: .
      dockerfile: packages/health-checker/Dockerfile
    restart: unless-stopped
    environment:
      <<: *common-environment
    ports:
      - '2025:2025'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    
  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
