version: '3.8'

x-common-environment: &common-environment
  NODE_ENV: production
  RPC_URLS: ${RPC_URLS}
  REDIS_HOST: redis-server
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  MULTICALL_BATCH_SIZE: ${MULTICALL_BATCH_SIZE}
  RPC_FIRST_PROBABILITY: ${RPC_FIRST_PROBABILITY}

services:
  redis-server:
    image: redis:latest
    mem_limit: 350m
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

  collector:
    build:
      context: .
      dockerfile: packages/collector/Dockerfile
    environment:
      <<: *common-environment
      FORK_RPC_URL: ${FORK_RPC_URL}
      NODE_OPTIONS: --max_old_space_size=256
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  liquidation-checker-eth-dominance:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: ETH Dominance
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_ETH_DOMINANCE}
      WORKERS_AMOUNT: ${WORKERS_AMOUNT_ETH_DOMINANCE}
      CRON_SCHEDULE: ${CRON_SCHEDULE_ETH_DOMINANCE}
      NODE_OPTIONS: --max_old_space_size=1024
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M

  liquidation-checker-btc-dominance:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: BTC Dominance
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_BTC_DOMINANCE}
      WORKERS_AMOUNT: ${WORKERS_AMOUNT_BTC_DOMINANCE}
      CRON_SCHEDULE: ${CRON_SCHEDULE_BTC_DOMINANCE}
      NODE_OPTIONS: --max_old_space_size=1024
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M

  liquidation-checker-quantum-cats:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Quantum Cats
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_QUANTUM_CATS}
      WORKERS_AMOUNT: ${WORKERS_AMOUNT_QUANTUM_CATS}
      CRON_SCHEDULE: ${CRON_SCHEDULE_QUANTUM_CATS}
      NODE_OPTIONS: --max_old_space_size=512
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-cs2-skins:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: CS2 Skins
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_CS2_SKINS}
      WORKERS_AMOUNT: ${WORKERS_AMOUNT_CS2_SKINS}
      CRON_SCHEDULE: ${CRON_SCHEDULE_CS2_SKINS}
      NODE_OPTIONS: --max_old_space_size=768
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 768M

  liquidation-checker-bitcoin-frogs:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Bitcoin Frogs
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_BITCOIN_FROGS}
      WORKERS_AMOUNT: ${WORKERS_AMOUNT_BITCOIN_FROGS}
      CRON_SCHEDULE: ${CRON_SCHEDULE_BITCOIN_FROGS}
      NODE_OPTIONS: --max_old_space_size=512
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-ink:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: Ink
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_INK}
      WORKERS_AMOUNT: ${WORKERS_AMOUNT_INK}
      CRON_SCHEDULE: ${CRON_SCHEDULE_INK}
      NODE_OPTIONS: --max_old_space_size=512
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-nodemonkes:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: NodeMonkes
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_NODEMONKES}
      WORKERS_AMOUNT: ${WORKERS_AMOUNT_NODEMONKES}
      CRON_SCHEDULE: ${CRON_SCHEDULE_NODEMONKES}
      NODE_OPTIONS: --max_old_space_size=512
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  liquidation-checker-evindex:
    build:
      context: .
      dockerfile: packages/liquidation-checker/Dockerfile
    environment:
      <<: *common-environment
      MARKET: EvIndex
      POSITIONS_PER_RUN: ${POSITIONS_PER_RUN_EVINDEX}
      WORKERS_AMOUNT: ${WORKERS_AMOUNT_EVINDEX}
      CRON_SCHEDULE: ${CRON_SCHEDULE_EVINDEX}
      NODE_OPTIONS: --max_old_space_size=512
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  executor-1:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    environment:
      <<: *common-environment
      PRIVATE_KEYS: ${PRIVATE_KEYS_1}
      NODE_OPTIONS: --max_old_space_size=256
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  executor-2:
    build:
      context: .
      dockerfile: packages/executor/Dockerfile
    environment:
      <<: *common-environment
      PRIVATE_KEYS: ${PRIVATE_KEYS_2}
      NODE_OPTIONS: --max_old_space_size=256
    depends_on:
      - redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    
